### ISSUE TITLE
Display for Non-Electric Vehicles

### ISSUE THREAD

**Issue by stephenmelody** [Jargendas/MMM-MyBMW#8]
Hey @Jargendas !

Nice work on the latest update, fixes are working nicely.

Here's what my car looks like on my magic mirror:

![image](https://github.com/user-attachments/assets/b910d90a-82fb-4126-9eb7-c356391bd07c)

There's a few minor issues:

1 - I get an empty battery icon even if I set "showElectricPercentage" and "showElectricRange" to false. The battery icon shows no matter if those two config items are set false, true or not defined at all. My car isn't electric at all. It's petrol only.

2 - the petrol tank icon overlaps the car image a little, I'd suggest either adding some spacing (nice and easy), or some kind of "if" statement whereby it'll show the petrol range where the electric range / percentage is on your example (with the red i3).

3 - "Last updated a few seconds ago" is constant, it doesn't adjust to the passage of time. So it might have been 10 minutes since it updated, but it just says "a few seconds ago". I'd suggest perhaps changing this to "Last updated: $timestamp" so you know the absolute time it updated, rather than a relative one.

I appreciate all the work you do on this!

Steve.

**Comment by Jargendas** [comment]
Hi Steve,

thanks for the feedback, I only have electric cars available for testing, so I did not notice these things. I attempted to fix them on the `fix/minor-bugs` branch. Could you check if everything works as expected with that?

**Comment by stephenmelody** [comment]
Hi @Jargendas 

Looks like 1 and 3 are fixed, but 2 (the overlapping layout), went the wrong way and it overlaps more.

Is it possible to set the font of the "Last updated..." line to the same as the range and odometer? It's the only text on my whole mirror that is in a Bold weighting, and it stands out a little.

![image](https://github.com/user-attachments/assets/554284e6-4835-44cc-97d3-69ab2ef73c78)

**Comment by Jargendas** [comment]
Ah, I see, the bottom lines move up because the battery percentage is missing. How's it now? Also fixed the bold thing, didn't even notice.

**Comment by stephenmelody** [comment]
Thanks! I'd probably bump it down a little bit more, but it's better. Thanks for adjusting the font too!

![image](https://github.com/user-attachments/assets/d670dbf3-beb8-4fc3-9a9f-6d39c8bcc041)

**Comment by Jargendas** [comment]
Great, I'll merge it then - I will leave the label where it is, but you can easily tweak it by adding and modifying the following snippet to your `css/custom.css`:

```
.MMM-MyBMW .bmw-container.spacer {
  height: 50px !important;
}
```

Have a nice new year's eve! :)

**Comment by stephenmelody** [comment]
Awesome! I’ll pull the main branch later.

Have a wonderful new year!!!
